//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class presentacion
    {
        public presentacion()
        {
            this.produccion = new HashSet<produccion>();
        }
    
        public int id { get; set; }
        [DisplayName("Nombre Presentación")]
        public string nombre { get; set; }
        [DisplayName("Mililitros")]
        public double mililitros { get; set; }
        [DisplayName("Valor Presentación")]
        public double valor_presentacion { get; set; }
    
        public virtual ICollection<produccion> produccion { get; set; }
    }
}
