//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class tipo_cerveza
    {
        public tipo_cerveza()
        {
            this.produccion = new HashSet<produccion>();
        }
    
        public int id { get; set; }
        [DisplayName("Tipo Cerveza")]
        public string nombre { get; set; }
        [DisplayName("Descripción")]
        public string descripcion { get; set; }
        [DisplayName("Nivel Alcohol")]
        public double alcohol { get; set; }
    
        public virtual ICollection<produccion> produccion { get; set; }
    }
}
